// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEO_SYSTEM_TECHNOLOGY.Data;

#nullable disable

namespace NEO_SYSTEM_TECHNOLOGY.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231024113930_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Contract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ContractSum")
                        .HasColumnType("int");

                    b.Property<int>("ContractType")
                        .HasColumnType("int");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("EnactmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Enactment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AmountValue")
                        .HasColumnType("int");

                    b.Property<int>("ContractID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnactmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExposedNfsDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NfsID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContractID")
                        .IsUnique();

                    b.ToTable("Enactments");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Enum.Receipt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("AmountFaceValue")
                        .HasColumnType("int");

                    b.Property<int>("ContractID")
                        .HasColumnType("int");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFaceValue")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVatIncluded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentSum")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContractID")
                        .IsUnique();

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Invoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceSum")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Nfs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("EnactmentID")
                        .HasColumnType("int");

                    b.Property<string>("NfsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnactmentID")
                        .IsUnique();

                    b.ToTable("Nfs");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Organization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ContractID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Contract", b =>
                {
                    b.HasOne("NEO_SYSTEM_TECHNOLOGY.Entity.Organization", "Organization")
                        .WithMany("Contracts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Enactment", b =>
                {
                    b.HasOne("NEO_SYSTEM_TECHNOLOGY.Entity.Contract", "Contract")
                        .WithOne("Enactment")
                        .HasForeignKey("NEO_SYSTEM_TECHNOLOGY.Entity.Enactment", "ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Enum.Receipt", b =>
                {
                    b.HasOne("NEO_SYSTEM_TECHNOLOGY.Entity.Contract", "Contract")
                        .WithOne("Receipt")
                        .HasForeignKey("NEO_SYSTEM_TECHNOLOGY.Entity.Enum.Receipt", "ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Invoice", b =>
                {
                    b.HasOne("NEO_SYSTEM_TECHNOLOGY.Entity.Contract", "Contract")
                        .WithOne("Invoice")
                        .HasForeignKey("NEO_SYSTEM_TECHNOLOGY.Entity.Invoice", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Nfs", b =>
                {
                    b.HasOne("NEO_SYSTEM_TECHNOLOGY.Entity.Enactment", "Enactment")
                        .WithOne("Nfs")
                        .HasForeignKey("NEO_SYSTEM_TECHNOLOGY.Entity.Nfs", "EnactmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enactment");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Person", b =>
                {
                    b.HasOne("NEO_SYSTEM_TECHNOLOGY.Entity.Organization", "Organization")
                        .WithMany("People")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Contract", b =>
                {
                    b.Navigation("Enactment");

                    b.Navigation("Invoice");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Enactment", b =>
                {
                    b.Navigation("Nfs");
                });

            modelBuilder.Entity("NEO_SYSTEM_TECHNOLOGY.Entity.Organization", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
